# docker-compose.yml
# =====================================
# Single port mapping to avoid duplicates.
# Using host port 75 mapped to container port 80.

version: '3.8'

services:
  static-site:
    # Build from the local Dockerfile
    build:
      context: .
      dockerfile: Dockerfile
    image: kaelnoer:latest

    # Mount local HTML directory for live-reload
    volumes:
      - ./html:/usr/share/nginx/html:ro

    # Only one port mapping. Change host port as needed.
    ports:
      - "3000"

    restart: always

# Usage:
# 1. Ensure this file and Dockerfile are in the same repo folder.
# 2. Commit to Git and set this path in Portainer Stack settings.
# 3. Deploy or redeploy the stack; your site listens on port 75.
# 4. On HTML changes (in ./html): docker-compose restart static-site
